---
abstract: 'XEP-0071: XHTML-IM (Version 1.5) for AnyEvent::XMPP'
author:
  - 'Charles McGarvey <ccm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-XMPP-Ext-HTML
requires:
  AnyEvent::XMPP::Ext: 0
  AnyEvent::XMPP::Namespaces: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/chazmcgarvey/p5-AnyEvent-XMPP-Ext-HTML.git
version: 0.02
